from parsers import parse_extracted_text_final,to_serializable
import json

if __name__ == "__main__":
    replace_list = [
        ("wo-chien","wo chien"),
        ("chien-pao","chien pao"),
        ("ting-lu","ting lu"),
        ("chi-yu","chi yu"),
        ("gimmighoul (chest form)","gimmighoul"),
        ("gimmighoul (roaming form)","gimmighoul roaming"),
        ("enamorus incarnate forme","enamorus"),
        ("enamorus therian forme","enamorus therian"),
        ("urshifu single strike form","urshifu"),
        ("urshifu rapid strike form","urshifu rapid strike style"),
        ("shllnotlc","shiinotic"),
        ("salandlt","salandit"),
        ("wishiwashi solo","wishiwashi"),
        ("wishiwashi schooling","wishiwashi school"),
        ("nolvern","noivern"),
        ("nolbat","noibat"),
        ("mareanle","mareanie"),
        ("fomantls","fomantis"),
        ("lurantls","lurantis"),
        ("bergmlte","bergmite"),
        ("gourgelst","gourgeist"),
        ("meowstic (m)","meowstic"),
        ("meowstic (f)","meowstic female"),
        ("sklddo","skiddo"),
        ("lltleo","litleo"),
        ("dlggersby","diggersby"),
        ("kyurem normal forme","kyurem"),
        ("kyurem white fusion forme","kyurem white"),
        ("kyurem black fusion forme","kyurem black"),
        ("landorus incarnate forme","landorus"),
        ("landorus therian forme","landorus therian"),
        ("thundurus incarnate forme","thundurus"),
        ("thundurus therian forme","thundurus therian"),
        ("tornadus incarnate forme","tornadus"),
        ("tornadus therian forme","tornadus therian"),
        ("bravlary","braviary"),
        ("beartlc","beartic"),
        ("deerllng","deerling"),
        ("speed:3","reuniclus"),
        ("trubblsh","trubbish"),
        ("mlncclno","minccino"),
        ("clncclno","cinccino"),
        ("petllll","petilil"),
        ("darmanitan galar, zen mode","darmanitan zen mode galar"),
        ("darmanltan standard mode","darmanitan"),
        ("darmanltan zen mode","darmanitan zen"),
        ("darmanitan galar, standard mode","darmanitan galar"),
        ("basculegion male","basculegion"),
        ("basculegion female","basculegion f"),
        ("lllllgant","lilligant"),
        ("excadrlll","excadrill"),
        ("whlmslcott","whimsicott"),
        ("slmlsage","simisage"),
        ("drllbur","drilbur"),
        ("slmlsear","simisear"),
        ("mlsmaglus","mismagius"),
        ("llcklllcky","lickilicky"),
        ("toxlcroak","toxicroak"),
        ("draplon","drapion"),
        ("skorupl","skorupi"),
        ("hlppowdon","hippowdon"),
        ("hlppopotas","hippopotas"),
        ("chlngllng","chingling"),
        ("drlfloon","drifloon"),
        ("drlfbllm","drifblim"),
        ("amblpom","ambipom"),
        ("cherubl","cherubi"),
        ("cherrlm","cherrim"),
        ("bldoof","bidoof"),
        ("blbarel","bibarel"),
        ("ratlcate","raticate"),
        ("dlglett","diglett"),
        ("dugtrlo","dugtrio"),
        ("perslan","persian"),
        ("dodrlo","dodrio"),
        ("llckltung","lickitung"),
        ("grlmer","grimer"),
        ("kofflng","koffing"),
        ("weezlng","weezing"),
        ("mlme jr.", "mime jr."),
        ("giratina origin forme", "giratina origin"),
        ("shaymin land forme", "shaymin"),
        ("shaymin sky forme", "shaymin sky"),
        ("mr. mime galar", "mr mime galar"),
        ("rotom normal form", "rotom"),
        ("mr. mlme", "mr. mime"),
        ("mlsdreavus","misdreavus"),
        ("alpom","aipom"),
        ("gllgar","gligar"),
        ("gllscor","gliscor"),
        ("teddlursa","teddiursa"),
        ("ursarlng","ursaring"),
        ("zlgzagoon","zigzagoon"),
        ("llnoone","linoone"),
        ("talllow","taillow"),
        ("shroomlsh","shroomish"),
        ("skltty","skitty"),
        ("gulpln","gulpin"),
        ("spolnk","spoink"),
        ("grumplg","grumpig"),
        ("altarla","altaria"),
        ("chlmecho","chimecho"),
        ("glalle","glalie"),
        ("deoxys normal forme","deoxys"),
        ("wormadam sandy cloak","wormadam sandy"),
        ("wormadam plant cloak","wormadam"),
        ("wormadam trash cloak","wormadam trash"),
        ("deoxys attack forme","deoxys attack"),
        ("deoxys defense forme","deoxys defense"),
        ("deoxys speed forme","deoxys speed"),
        ("deoxys speed forme","deoxys speed"),
    ]
    with open("data/db_pokedex.json", "r") as f:
        db_pokemons = json.load(f)
    db_pokemons_names = list(filter(lambda x: x["name"]["english"].lower(),db_pokemons))
    #range_gen_7 = range(32,33)
    range_gen_7 = range(0,201)
    pdf_gen_7 = "data/output_part1.pdf"
    pokemons = []
    loaded_mons = parse_extracted_text_final(pdf_gen_7, range_gen_7,db_pokemons_names)
    if loaded_mons is not None:
        for mon in loaded_mons:
            pokemons.append(mon)
    print(str(len(pokemons))+" pokemons")
    with open("output/finals/pokemons.json", "w", encoding="utf-8") as f:
        json.dump(
            to_serializable(pokemons),
            f,
            indent=4,  # pretty print
            ensure_ascii=False
        )
