#!/usr/bin/env python3
"""
Génère list_pokemon_finished.txt en indiquant si chaque Pokémon
pourrait avoir des attaques de type Son, avec justification.
"""

import re

# ─── Dictionnaire explicite (pokemon en minuscules) ─────────────────────────
# Format: "nom": ("OUI"/"NON"/"PEUT-ÊTRE", "justification")

SOUND_DATA = {
    # ── Starters Plante ──────────────────────────────────────────────────────
    "bulbasaur": ("NON", "plante/poison, communication par spores sans lien au son"),
    "ivysaur": ("NON", "même base que Bulbizarre, florissant mais silencieux"),
    "venusaur": ("NON", "libère des arômes, pas de mécanisme sonore notable"),
    "chikorita": ("NON", "feuille aromatique, pas de lien au son"),
    "bayleef": ("NON", "idem, col de feuilles parfumées"),
    "meganium": ("PEUT-ÊTRE", "son souffle de fleur apaise les gens, pourrait émettre des ultrasons"),
    "treecko": ("NON", "lézard bois silencieux"),
    "grovyle": ("NON", "idem, furtif"),
    "sceptile": ("NON", "guerrier végétal silencieux"),
    "turtwig": ("NON", "tortue plante"),
    "grotle": ("NON", "idem"),
    "torterra": ("NON", "forêt vivante, tremblements de terre mais pas sonore"),
    "snivy": ("NON", "serpent plante hautain et silencieux"),
    "servine": ("NON", "idem"),
    "serperior": ("NON", "regard hypnotique mais pas sonore"),
    "chespin": ("NON", "hérisson plante"),
    "quilladin": ("NON", "idem"),
    "chesnaught": ("NON", "chevalier végétal"),
    "rowlet": ("NON", "chouette plante, silencieuse et furtive"),
    "dartrix": ("NON", "idem"),
    "decidueye": ("NON", "archer fantôme silencieux"),
    "decidueye hisuian": ("NON", "combattant martial silencieux"),
    # ── Starters Feu ─────────────────────────────────────────────────────────
    "charmander": ("NON", "lézard feu basique"),
    "charmeleon": ("NON", "idem"),
    "charizard": ("PEUT-ÊTRE", "rugissements impressionnants de dragon"),
    "cyndaquil": ("NON", "petit hérisson feu),"),
    "quilava": ("NON", "idem"),
    "typhlosion": ("PEUT-ÊTRE", "rugissements intenses selon le Pokédex"),
    "torchic": ("NON", "poussin feu"),
    "combusken": ("NON", "idem"),
    "blaziken": ("PEUT-ÊTRE", "cri de combat puissant"),
    "chimchar": ("NON", "petit singe feu"),
    "monferno": ("NON", "idem"),
    "infernape": ("NON", "guerrier agile"),
    "tepig": ("NON", "cochon feu"),
    "pignite": ("NON", "idem"),
    "emboar": ("NON", "idem"),
    "fennekin": ("NON", "renard feu"),
    "braixen": ("NON", "idem"),
    "delphox": ("PEUT-ÊTRE", "sorcière qui murmure des incantations"),
    "litten": ("NON", "chat feu silencieux"),
    "torracat": ("NON", "idem, ronronnement mais pas offensif"),
    "incineroar": ("OUI", "catcheur avec cris d'intimidation, Bulk Up via roar"),
    # ── Starters Eau ─────────────────────────────────────────────────────────
    "squirtle": ("NON", "tortue eau"),
    "wartortle": ("NON", "idem"),
    "blastoise": ("NON", "canons à eau, pas de son"),
    "totodile": ("NON", "crocodile eau"),
    "croconaw": ("NON", "idem"),
    "feraligatr": ("NON", "idem"),
    "mudkip": ("NON", "axolotl eau"),
    "marshtomp": ("NON", "idem"),
    "swampert": ("NON", "idem"),
    "piplup": ("NON", "manchot eau"),
    "prinplup": ("NON", "idem"),
    "empoleon": ("NON", "idem"),
    "oshawott": ("NON", "loutre eau"),
    "dewott": ("NON", "idem"),
    "samurott": ("NON", "samouraï eau silencieux"),
    "samurott hisuian": ("NON", "idem"),
    "froakie": ("PEUT-ÊTRE", "grenouille, cri de grenouille possible"),
    "frogadier": ("PEUT-ÊTRE", "idem"),
    "greninja": ("PEUT-ÊTRE", "ninja silencieux mais cris d'arts martiaux"),
    "ash-greninja": ("PEUT-ÊTRE", "idem"),
    "popplio": ("OUI", "otarie chanteuse, fait des ballons de son et chante"),
    "brionne": ("OUI", "danseuse chanteuse, mélodie magique"),
    "primarina": ("OUI", "prima donna opératique, attaque avec des chants et des sphères sonores"),
    # ── Chenilles/Papillons ───────────────────────────────────────────────────
    "caterpie": ("NON", "chenille basique"),
    "metapod": ("NON", "chrysalide immobile"),
    "butterfree": ("NON", "papillon, écailles silencieuses"),
    "weedle": ("NON", "chenille venimeuse"),
    "kakuna": ("NON", "cocon"),
    "beedrill": ("PEUT-ÊTRE", "abeille, bourdonnement d'ailes à haute fréquence"),
    "wurmple": ("NON", "chenille"),
    "silcoon": ("NON", "cocon"),
    "beautifly": ("NON", "papillon"),
    "cascoon": ("NON", "cocon"),
    "dustox": ("NON", "papillon nocturne"),
    "sewaddle": ("NON", "chenille"),
    "swadloon": ("NON", "cocon"),
    "leavanny": ("NON", "tailleur insecte silencieux"),
    "venipede": ("NON", "mille-pattes"),
    "whirlipede": ("NON", "idem"),
    "scolipede": ("NON", "grand mille-pattes"),
    "scatterbug": ("NON", "chenille"),
    "spewpa": ("NON", "cocon"),
    "vivillon": ("NON", "papillon"),
    "grubbin": ("NON", "larve"),
    "charjabug": ("NON", "cocon électrique"),
    "vikavolt": ("PEUT-ÊTRE", "scarabée électrique, vrombissement d'ailes"),
    # ── Dragon Faux ──────────────────────────────────────────────────────────
    "axew": ("NON", "petit dragon défenses"),
    "fraxure": ("NON", "idem"),
    "haxorus": ("NON", "guerrier dragon"),
    # ── Électriques ──────────────────────────────────────────────────────────
    "pichu": ("OUI", "couinements électriques, apprentissage du son"),
    "pikachu": ("OUI", "cris caractéristiques, Thunder Shock avec sons"),
    "raichu": ("OUI", "idem, ondes électriques émises comme signaux sonores"),
    "raichu alola": ("OUI", "idem, surfe sur des ondes psychiques/sonores"),
    "magnemite": ("PEUT-ÊTRE", "génère des champs magnétiques, bourdonnement électrique"),
    "magneton": ("PEUT-ÊTRE", "idem, signal radio"),
    "magnezone": ("PEUT-ÊTRE", "génère des ondes électromagnétiques"),
    "elekid": ("NON", "électrique, pas sonore"),
    "electabuzz": ("NON", "idem"),
    "electivire": ("NON", "idem"),
    "mareep": ("NON", "mouton électrique"),
    "flaaffy": ("NON", "idem"),
    "ampharos": ("PEUT-ÊTRE", "phare lumineux, mais signal de guidage = signal sonore possible"),
    "shinx": ("NON", "lionceau électrique"),
    "luxio": ("NON", "idem"),
    "luxray": ("NON", "idem"),
    "tynamo": ("NON", "lamproie électrique"),
    "eelektrik": ("NON", "anguille électrique"),
    "eelektross": ("NON", "idem"),
    # ── Fées / Normaux chanteurs ──────────────────────────────────────────────
    "cleffa": ("OUI", "couinements cristallins lors des pluies de météorites"),
    "clefairy": ("OUI", "danse et chante lors des nuits de pleine lune"),
    "clefable": ("OUI", "idem, sensible aux sons ultrasoniques"),
    "togepi": ("PEUT-ÊTRE", "bienveillant, petits cris joyeux"),
    "togetic": ("PEUT-ÊTRE", "idem"),
    "togekiss": ("PEUT-ÊTRE", "cri d'harmonie apaisant"),
    "flabébé": ("NON", "fée florale silencieuse"),
    "floette": ("NON", "idem"),
    "florges": ("NON", "idem"),
    # ── Combat ───────────────────────────────────────────────────────────────
    "machop": ("NON", "combattant physique"),
    "machoke": ("NON", "idem"),
    "machamp": ("NON", "idem"),
    "timburr": ("NON", "idem"),
    "gurdurr": ("NON", "idem"),
    "conkeldurr": ("NON", "idem"),
    "magby": ("NON", "bébé feu"),
    "magmar": ("NON", "feu"),
    "magmortar": ("NON", "feu"),
    # ── Feu/Vol ───────────────────────────────────────────────────────────────
    "fletchling": ("NON", "rouge-gorge feu silencieux"),
    "fletchinder": ("NON", "idem"),
    "talonflame": ("PEUT-ÊTRE", "faucon, cris d'oiseau en piqué"),
    # ── Fantômes ─────────────────────────────────────────────────────────────
    "gastly": ("PEUT-ÊTRE", "murmures fantomatiques"),
    "haunter": ("OUI", "gémissements et murmures terrifiants selon le Pokédex"),
    "gengar": ("OUI", "rires et cris maléfiques, Perish Song naturel"),
    "duskull": ("NON", "fantôme silencieux"),
    "dusclops": ("NON", "idem"),
    "dusknoir": ("NON", "idem"),
    "litwick": ("NON", "flamme fantôme silencieuse"),
    "lampent": ("NON", "idem"),
    "chandelure": ("NON", "flammes aspirant les âmes, pas sonore"),
    # ── Plantes/Poison ───────────────────────────────────────────────────────
    "oddish": ("NON", "plante"),
    "gloom": ("NON", "plante"),
    "vileplume": ("NON", "plante"),
    "bellossom": ("OUI", "danse au son des tambours lors des rituels"),
    "bellsprout": ("NON", "plante carnivore"),
    "weepinbell": ("NON", "idem"),
    "victreebel": ("NON", "plante piège"),
    "hoppip": ("NON", "plante volante"),
    "skiploom": ("NON", "idem"),
    "jumpluff": ("NON", "idem"),
    "seedot": ("NON", "gland"),
    "nuzleaf": ("NON", "idem"),
    "shiftry": ("OUI", "ses feuilles-éventails créent des vents et sons mystérieux"),
    "budew": ("NON", "bouton floral"),
    "roselia": ("NON", "fleur"),
    "roserade": ("NON", "idem"),
    "bounsweet": ("NON", "fruit"),
    "steenee": ("NON", "idem"),
    "tsareena": ("NON", "plante aristocratique"),
    # ── Roche/Sol ────────────────────────────────────────────────────────────
    "rhyhorn": ("NON", "rhinocéros roche"),
    "rhydon": ("NON", "idem"),
    "rhyperior": ("NON", "idem"),
    # ── Combat/Normal ────────────────────────────────────────────────────────
    "mankey": ("PEUT-ÊTRE", "singe colérique, cris de rage"),
    "primeape": ("PEUT-ÊTRE", "idem, hurlements de rage"),
    "tyrogue": ("NON", "boxeur"),
    "hitmonlee": ("NON", "karatéka"),
    "hitmonchan": ("NON", "boxeur"),
    "hitmontop": ("NON", "toupie"),
    "makuhita": ("NON", "lutteur"),
    "hariyama": ("NON", "idem"),
    "meditite": ("NON", "méditant"),
    "medicham": ("NON", "idem"),
    "riolu": ("OUI", "détecte l'aura, émet des ondes d'énergie intérieure"),
    "lucario": ("OUI", "maîtrise de l'aura transmise par ondes, crie en combat"),
    "mienfoo": ("NON", "guerrier agile"),
    "mienshao": ("NON", "idem"),
    "pancham": ("NON", "panda"),
    "pangoro": ("NON", "idem"),
    "crabrawler": ("NON", "crabe boxeur"),
    "crabominable": ("NON", "crabe des neiges"),
    # ── Feu ──────────────────────────────────────────────────────────────────
    "vulpix": ("PEUT-ÊTRE", "cris aigus de renard"),
    "ninetales": ("PEUT-ÊTRE", "malédictions murmurées selon le Pokédex"),
    "growlithe": ("PEUT-ÊTRE", "aboiements"),
    "arcanine": ("OUI", "rugissements majestueux selon le Pokédex"),
    "ponyta": ("NON", "cheval feu"),
    "rapidash": ("NON", "idem"),
    "slugma": ("NON", "magma"),
    "magcargo": ("NON", "idem"),
    "trapinch": ("NON", "fourmi-lion"),
    "vibrava": ("OUI", "vibrations ultrasoniques de ses ailes qui causent des maux de tête"),
    "flygon": ("OUI", "chant mélodieux créé par ses ailes surnommé 'esprit du désert'"),
    "sandile": ("NON", "crocodile sable"),
    "krokorok": ("NON", "idem"),
    "krookodile": ("NON", "idem"),
    "swinub": ("NON", "cochon glace"),
    "piloswine": ("NON", "idem"),
    "mamoswine": ("NON", "mammouth"),
    "spheal": ("NON", "phoque glace"),
    "sealeo": ("PEUT-ÊTRE", "phoque qui jongle, claps sonores"),
    "walrein": ("PEUT-ÊTRE", "morse, barrissements"),
    "vanillite": ("NON", "glace"),
    "vanillish": ("NON", "idem"),
    "vanilluxe": ("NON", "idem"),
    # ── Vol/Normal ────────────────────────────────────────────────────────────
    "pidgey": ("NON", "oiseau basique"),
    "pidgeotto": ("NON", "idem"),
    "pidgeot": ("NON", "idem"),
    "starly": ("NON", "étourneau"),
    "staravia": ("NON", "idem"),
    "staraptor": ("PEUT-ÊTRE", "cri de guerre puissant"),
    "lillipup": ("NON", "chiot"),
    "herdier": ("NON", "idem"),
    "stoutland": ("NON", "idem"),
    "pidove": ("NON", "pigeon"),
    "tranquill": ("NON", "idem"),
    "unfezant": ("NON", "faisan"),
    "pikipek": ("OUI", "frappe les arbres à 16 coups/seconde, son de tambourinage"),
    "trumbeak": ("OUI", "bec trompette, cris stridents comme klaxon"),
    "toucannon": ("OUI", "canon-toucan, souffle bruyant et percutant"),
    # ── Normal chanteurs ──────────────────────────────────────────────────────
    "igglybuff": ("OUI", "bébé chanteur, voix qui endort"),
    "jigglypuff": ("OUI", "chante pour endormir, attaque iconique de type Son"),
    "wigglytuff": ("OUI", "idem, voix encore plus puissante"),
    "happiny": ("PEUT-ÊTRE", "bébé chansey"),
    "chansey": ("PEUT-ÊTRE", "chante doucement pour réconforter"),
    "blissey": ("PEUT-ÊTRE", "idem, cri d'amour"),
    "porygon": ("NON", "Pokémon numérique"),
    "porygon2": ("NON", "idem"),
    "porygon-z": ("NON", "idem"),
    "slakoth": ("NON", "paresseux"),
    "vigoroth": ("NON", "idem"),
    "slaking": ("NON", "idem"),
    "whismur": ("OUI", "crie tellement fort quand effrayé qu'il s'assourdit lui-même"),
    "loudred": ("OUI", "hurle avec une force dévastatrice"),
    "exploud": ("OUI", "émetteur sonore ultime, tuyaux corporels amplifient tout"),
    # ── Oiseaux chanteurs ─────────────────────────────────────────────────────
    "chatot": ("OUI", "perroquet musical, copie et chante, Chatter exclusif"),
    "hoothoot": ("OUI", "hululements nocturnes précis comme une horloge"),
    "noctowl": ("OUI", "ultrasons pour localiser les proies"),
    "doduo": ("PEUT-ÊTRE", "deux têtes crient en même temps"),
    "dodrio": ("PEUT-ÊTRE", "trois têtes en harmonie (triste/joyeux/furieux)"),
    "swablu": ("OUI", "chante doucement comme le nuage, voix apaisante"),
    "altaria": ("OUI", "chant d'alto mélodieux qui enveloppe les êtres"),
    # ── Psychiques ───────────────────────────────────────────────────────────
    "abra": ("NON", "téléportation silencieuse"),
    "kadabra": ("NON", "idem"),
    "alakazam": ("NON", "idem"),
    "ralts": ("PEUT-ÊTRE", "perçoit les émotions sous forme de vibrations"),
    "kirlia": ("PEUT-ÊTRE", "idem"),
    "gardevoir": ("PEUT-ÊTRE", "champ de distorsion, mais pas sonore en soi"),
    "gallade": ("NON", "chevalier psychique"),
    "gothita": ("NON", "poupée psychique"),
    "gothorita": ("NON", "idem"),
    "gothitelle": ("NON", "idem"),
    "solosis": ("NON", "cellule psychique"),
    "duosion": ("NON", "idem"),
    "reuniclus": ("NON", "idem"),
    "espurr": ("PEUT-ÊTRE", "cris muets effrayants selon le Pokédex"),
    "meowstic": ("PEUT-ÊTRE", "idem"),
    "meowstic female": ("PEUT-ÊTRE", "idem"),
    "drowzee": ("OUI", "fredonne pour endormir, hypnose par mélodie"),
    "hypno": ("OUI", "balancement de pendule avec berceuse murmurée"),
    "mime jr.": ("PEUT-ÊTRE", "mime mais imite aussi les sons"),
    "mr. mime": ("PEUT-ÊTRE", "idem"),
    "mr mime": ("PEUT-ÊTRE", "idem"),
    "mr. rime": ("OUI", "danse et chante des rimes"),
    "mr mime galar": ("OUI", "chante et danse"),
    "natu": ("NON", "oiseau psychique"),
    "xatu": ("NON", "idem"),
    "wynaut": ("NON", "idem"),
    "wobbuffet": ("NON", "idem"),
    "spoink": ("OUI", "rebondit en rythme, son des ressorts et son cœur peut s'arrêter s'il cesse"),
    "grumpig": ("OUI", "danse au rythme de perles noires magiques"),
    "chingling": ("OUI", "grelot qui tinte, son magique"),
    "chimecho": ("OUI", "carillon qui chante le vent, voix mélodieuse"),
    "munna": ("NON", "psychique floral"),
    "musharna": ("NON", "idem"),
    "woobat": ("OUI", "chauve-souris, ultrasons du nez"),
    "swoobat": ("OUI", "idem, ondes sonores d'amour"),
    "elgyem": ("NON", "alien"),
    "beheeyem": ("NON", "idem"),
    # ── Roche ────────────────────────────────────────────────────────────────
    "geodude": ("NON", "roche"),
    "graveler": ("NON", "idem"),
    "golem": ("NON", "idem"),
    "roggenrolla": ("NON", "roche"),
    "roggenrola": ("NON", "roche"),
    "boldore": ("NON", "idem"),
    "gigalith": ("NON", "idem"),
    "aron": ("NON", "acier/roche"),
    "lairon": ("NON", "idem"),
    "aggron": ("PEUT-ÊTRE", "rugissements de dinosaure métal"),
    "klink": ("PEUT-ÊTRE", "engrenages qui cliquètent"),
    "klang": ("PEUT-ÊTRE", "idem"),
    "klinklang": ("PEUT-ÊTRE", "idem"),
    "onix": ("NON", "serpent rocheux"),
    "steelix": ("NON", "idem"),
    "nosepass": ("NON", "boussole roche"),
    "probopass": ("NON", "idem"),
    "bonsly": ("NON", "bonsaï roche"),
    "sudowoodo": ("NON", "idem"),
    "binacle": ("NON", "bernacle"),
    "barbaracle": ("NON", "idem"),
    "rockruff": ("NON", "chiot roche"),
    "lycanroc midday": ("NON", "loup roche"),
    "lycanroc midnight": ("NON", "idem"),
    "lycanroc dusk": ("NON", "idem"),
    "lycanroc": ("NON", "idem"),
    "lycanroc eclipse": ("NON", "idem"),
    "lycanroc twilight": ("NON", "idem"),
    "bronzor": ("PEUT-ÊTRE", "gong antique, résonne"),
    "bronzong": ("OUI", "cloche de bronze, tinte et résonne pour appeler la pluie"),
    # ── Eau ──────────────────────────────────────────────────────────────────
    "psyduck": ("NON", "canard maux de tête"),
    "golduck": ("NON", "idem"),
    "tentacool": ("NON", "méduse"),
    "tentacruel": ("NON", "idem"),
    "slowpoke": ("NON", ("idem")),
    "slowbro": ("NON", "idem"),
    "slowking": ("NON", "idem"),
    "seel": ("PEUT-ÊTRE", "phoque, sons joyeux"),
    "dewgong": ("OUI", "dugong, chante des mélodies sous-marines"),
    "shellder": ("NON", "coquillage"),
    "cloyster": ("NON", "idem"),
    "krabby": ("NON", "crabe"),
    "kingler": ("NON", "idem"),
    "goldeen": ("NON", "poisson"),
    "seaking": ("NON", "idem"),
    "staryu": ("NON", "étoile de mer"),
    "starmie": ("NON", "idem"),
    "magikarp": ("NON", "poisson"),
    "gyarados": ("OUI", "rugissements terrifiants selon le Pokédex"),
    "chinchou": ("NON", "poisson lumière"),
    "lanturn": ("NON", "idem"),
    "wooper": ("NON", "axolotl"),
    "quagsire": ("NON", "idem"),
    "remoraid": ("NON", "poisson fusil"),
    "octillery": ("NON", "pieuvre"),
    "mantyke": ("NON", "raie"),
    "mantine": ("NON", "idem"),
    "wingull": ("PEUT-ÊTRE", "cri de mouette"),
    "pelipper": ("PEUT-ÊTRE", "cri de pélican"),
    "carvanha": ("NON", "piranha"),
    "sharpedo": ("NON", "requin"),
    "wailmer": ("OUI", "baleine, chante des mélodies sous-marines"),
    "wailord": ("OUI", "baleine géante, chants de baleine portent loin"),
    "barboach": ("NON", "loche"),
    "whiscash": ("NON", "idem"),
    "corphish": ("NON", "écrevisse"),
    "crawdaunt": ("NON", "idem"),
    "feebas": ("NON", "poisson laid"),
    "milotic": ("PEUT-ÊTRE", "beauté apaisante, chant doux possible"),
    "clamperl": ("NON", "coquillage"),
    "huntail": ("NON", "poisson abyssal"),
    "gorebyss": ("NON", "idem"),
    "buizel": ("NON", "loutre"),
    "floatzel": ("NON", "idem"),
    "shellos": ("NON", "limace mer"),
    "gastrodon": ("NON", "idem"),
    "finneon": ("NON", "poisson"),
    "lumineon": ("NON", "idem"),
    "panpour": ("NON", "singe eau"),
    "simipour": ("NON", "idem"),
    "ducklett": ("PEUT-ÊTRE", "caneton"),
    "swanna": ("OUI", "cygne, chant du cygne légendaire"),
    "frillish": ("NON", "méduse"),
    "jellicent": ("NON", "idem"),
    "clauncher": ("NON", "crevette"),
    "clawitzer": ("NON", "idem"),
    "dewpider": ("NON", "araignée aquatique"),
    "araquanid": ("NON", "idem"),
    "tympole": ("OUI", "tympano = tambour en grec, vibre pour communiquer"),
    "palpitoad": ("OUI", "vibrisse sur la tête génèrent des ondes sonores"),
    "seismitoad": ("OUI", "vibrissons amplifient les ondes, Seismic + Toad"),
    # ── Insectes ─────────────────────────────────────────────────────────────
    "pinsir": ("NON", "scarabée pince"),
    "shuckle": ("NON", "mollusque"),
    "heracross": ("NON", "scarabée hercule"),
    "volbeat": ("OUI", "luciole, émet des signaux lumineux et sonores synchronisés"),
    "illumise": ("OUI", "idem, attire par des parfums et signaux"),
    "durant": ("NON", "fourmi métal"),
    "paras": ("NON", "champignon/insecte"),
    "parasect": ("NON", "idem"),
    "venonat": ("NON", "insecte"),
    "venomoth": ("NON", "idem"),
    "scyther": ("NON", "mante"),
    "scizor": ("NON", "idem"),
    "ledyba": ("OUI", "communique par arômes ET sons pour se coordonner"),
    "ledian": ("NON", "idem, moins prononcé"),
    "spinarak": ("NON", "araignée"),
    "ariados": ("NON", "idem"),
    "yanma": ("PEUT-ÊTRE", "libellule, vrombissement d'ailes"),
    "yanmega": ("PEUT-ÊTRE", "idem, ailes créent ondes de choc"),
    "pineco": ("NON", "pomme de pin"),
    "forretress": ("NON", "idem"),
    "surskit": ("NON", "araignée eau"),
    "masquerain": ("NON", "idem"),
    "nincada": ("NON", "cigale larve"),
    "ninjask": ("OUI", "cigale, cri strident tellement fort qu'il peut paralyser"),
    "shedinja": ("NON", "mue fantôme silencieuse"),
    "kricketot": ("OUI", "cricket/grillon, collisions d'antennes = musique"),
    "kricketune": ("OUI", "grillon musicien, violon avec ses pattes"),
    "burmy": ("NON", "cocon déguisé"),
    "wormadam": ("NON", "idem"),
    "wormadam sandy": ("NON", "idem"),
    "wormadam trash": ("NON", "idem"),
    "mothim": ("NON", "papillon"),
    "combee": ("PEUT-ÊTRE", "abeille, bourdonnement"),
    "vespiquen": ("PEUT-ÊTRE", "reine des abeilles, signal sonore de ruche"),
    "dwebble": ("NON", "bernard-l'hermite roche"),
    "crustle": ("NON", "idem"),
    "karrablast": ("NON", "coléoptère"),
    "escavalier": ("NON", "idem"),
    "shelmet": ("NON", "idem"),
    "accelgor": ("NON", "idem"),
    "joltik": ("NON", "tique électrique"),
    "galvantula": ("PEUT-ÊTRE", "araignée électrique, vibrations de toile"),
    "larvesta": ("NON", "larve feu"),
    "volcarona": ("NON", "papillon feu"),
    "cutiefly": ("NON", "mouche"),
    "ribombee": ("PEUT-ÊTRE", "bourdonnement d'ailes"),
    "wimpod": ("NON", "cloporte"),
    "golisopod": ("NON", "idem"),
    # ── Ténèbres ─────────────────────────────────────────────────────────────
    "murkrow": ("PEUT-ÊTRE", "corbeau, croasse"),
    "honchkrow": ("PEUT-ÊTRE", "idem, boss mafieux"),
    "sneasel": ("NON", "belette"),
    "weavile": ("NON", "idem"),
    "houndour": ("OUI", "hurle en meute pour communiquer"),
    "houndoom": ("OUI", "hurlement glaçant selon le Pokédex"),
    "poochyena": ("PEUT-ÊTRE", "aboiements"),
    "mightyena": ("PEUT-ÊTRE", "idem"),
    "purrloin": ("NON", "chat voleur"),
    "liepard": ("NON", "idem"),
    "scraggy": ("NON", "lézard pantalon"),
    "scrafty": ("NON", "idem"),
    "zorua": ("NON", "renard illusion"),
    "zoroark": ("NON", "idem"),
    "pawniard": ("NON", "acier tranchant"),
    "bisharp": ("NON", "idem"),
    "vullaby": ("NON", "vautour"),
    "mandibuzz": ("NON", "idem"),
    "inkay": ("NON", "pieuvre"),
    "malamar": ("NON", "idem"),
    # ── Électrique non-son ────────────────────────────────────────────────────
    "voltorb": ("PEUT-ÊTRE", "bombe, bruit d'explosion"),
    "electrode": ("PEUT-ÊTRE", "idem"),
    "electrike": ("NON", "chien électrique"),
    "manectric": ("NON", "idem"),
    "blitzle": ("NON", "zèbre électrique"),
    "zebstrika": ("PEUT-ÊTRE", "hennissement électrique"),
    "helioptile": ("NON", "lézard solaire"),
    "heliolisk": ("NON", "idem"),
    "snubbull": ("NON", "bulldog"),
    "granbull": ("PEUT-ÊTRE", "aboiements intimidants"),
    "spritzee": ("NON", "fée parfum"),
    "aromatisse": ("NON", "idem"),
    "swirlix": ("NON", "barbe à papa"),
    # ── Feu/Normal ───────────────────────────────────────────────────────────
    "numel": ("NON", "chameau feu"),
    "camerupt": ("NON", "idem"),
    "pansear": ("NON", "singe feu"),
    "simisear": ("NON", "idem"),
    "darumaka": ("NON", "daruma feu"),
    "darmanitan": ("NON", "idem"),
    "darmanitan zen": ("NON", "idem"),
    "litleo": ("PEUT-ÊTRE", "lionceau, rugissements"),
    "pyroar": ("OUI", "rugissements à 18 000°C selon le Pokédex, son emblématique"),
    # ── Dragon/Vol ───────────────────────────────────────────────────────────
    "noibat": ("OUI", "chauve-souris dragon, ultrasons à 200 000 Hz"),
    "noivern": ("OUI", "dragon sonar, attaque avec des ultrasons dévastateurs"),
    # ── Fantôme/Plante ───────────────────────────────────────────────────────
    "misdreavus": ("OUI", "se nourrit des cris de terreur, gémissements fantômes"),
    "mismagius": ("OUI", "incantations et chants maléfiques"),
    "shuppet": ("NON", "fantôme rancunier"),
    "banette": ("NON", "poupée vaudou"),
    "drifloon": ("NON", "ballon fantôme"),
    "drifblim": ("NON", "idem"),
    "yamask": ("NON", "masque fantôme"),
    "cofagrlgus": ("NON", "sarcophage"),
    "cofagrigus": ("NON", "sarcophage"),
    "phantump": ("OUI", "gémissements d'enfant perdu dans la forêt"),
    "trevenant": ("OUI", "idem, arbres qui craquent et gémissent"),
    "pumpkaboo": ("PEUT-ÊTRE", "citrouille fantôme"),
    "gourgeist": ("OUI", "chante à la pleine lune pour maudire"),
    "sandygast": ("NON", "château de sable"),
    "palossand": ("NON", "idem"),
    # ── Plante/Eau ───────────────────────────────────────────────────────────
    "exeggcute": ("NON", "œufs plant"),
    "exeggutor": ("NON", "idem"),
    "exeggutor alola": ("NON", "idem"),
    "tangela": ("NON", "lianes"),
    "tangrowth": ("NON", "idem"),
    "sunkern": ("NON", "graine"),
    "sunflora": ("NON", "tournesol"),
    "shroomish": ("NON", "champignon"),
    "breloom": ("NON", "kangourou champignon"),
    "cacnea": ("NON", "cactus"),
    "cacturne": ("NON", "idem"),
    "cherubi": ("NON", "cerise"),
    "cherrim": ("NON", "idem"),
    "snover": ("NON", "arbre neige"),
    "abomasnow": ("NON", "idem"),
    "pansage": ("NON", "singe plante"),
    "simisage": ("NON", "idem"),
    "cottonee": ("NON", "coton"),
    "whimsicott": ("NON", "idem"),
    "petilil": ("NON", "bulbe floral"),
    "lilligant": ("NON", "idem"),
    "foongus": ("NON", "champignon"),
    "amoonguss": ("NON", "idem"),
    "ferroseed": ("NON", "graine épine"),
    "ferrothorn": ("NON", "idem"),
    "skiddo": ("NON", "chèvre"),
    "gogoat": ("NON", "idem"),
    "fomantis": ("NON", "mante faucille"),
    "lurantis": ("NON", "idem"),
    "morelull": ("NON", "champignon nocturne"),
    "shiinotic": ("NON", "idem"),
    # ── Sol ──────────────────────────────────────────────────────────────────
    "sandshrew": ("NON", "pangolin sable"),
    "sandslash": ("NON", "idem"),
    "diglett": ("NON", "taupe"),
    "dugtrio": ("NON", "idem"),
    "cubone": ("NON", "petit roche"),
    "marowak": ("NON", "idem"),
    "marowak alola": ("PEUT-ÊTRE", "os-tambour en feu, percussions rituelles"),
    "gligar": ("NON", "chauve-souris roche"),
    "gliscor": ("NON", "idem"),
    "phanpy": ("NON", "éléphanteau"),
    "donphan": ("NON", "idem"),
    "baltoy": ("NON", "argile"),
    "claydol": ("NON", "idem"),
    "hippopotas": ("NON", "hippopotame sable"),
    "hippowdon": ("NON", "idem"),
    "drilbur": ("NON", "taupe"),
    "excadrill": ("NON", "idem"),
    "golett": ("NON", "golem argile"),
    "golurk": ("NON", "idem"),
    "mudbray": ("NON", "âne boue"),
    "mudsdale": ("NON", "idem"),
    # ── Glace ────────────────────────────────────────────────────────────────
    "smoochum": ("OUI", "fredonne et chante pour développer son sens du rythme"),
    "jynx": ("OUI", "chante une mélodie incompréhensible qui fait bouger involontairement"),
    "snorunt": ("NON", "capuche glace"),
    "glalie": ("NON", "sphère glace"),
    "froslass": ("PEUT-ÊTRE", "lamentations fantôme/glace"),
    "cubchoo": ("PEUT-ÊTRE", "renifle constamment"),
    "beartic": ("NON", "ours polaire"),
    "bergmite": ("NON", "glace"),
    "avalugg": ("NON", "iceberg"),
    # ── Normal ───────────────────────────────────────────────────────────────
    "rattata": ("NON", "rat"),
    "raticate": ("NON", "idem"),
    "spearow": ("PEUT-ÊTRE", "cris perçants"),
    "fearow": ("PEUT-ÊTRE", "idem, cri terrifiant"),
    "meowth": ("OUI", "miaulements pour bercer, Perish Song"),
    "persian": ("OUI", "ronronnement/maulement aristocratique"),
    "lickitung": ("NON", "langue"),
    "lickilicky": ("NON", "idem"),
    "munchlax": ("NON", "goinfre"),
    "snorlax": ("OUI", "ronflement légendaire selon le Pokédex, snore = Ronflement"),
    "sentret": ("NON", "vigie"),
    "furret": ("NON", "idem"),
    "aipom": ("NON", "singe queue"),
    "ambipom": ("NON", "idem"),
    "teddiursa": ("NON", "ourson"),
    "ursaring": ("NON", "idem"),
    "zigzagoon": ("NON", "raton laveur"),
    "linoone": ("NON", "idem"),
    "taillow": ("NON", "hirondelle"),
    "swellow": ("NON", "idem"),
    "skitty": ("NON", "chaton"),
    "delcatty": ("NON", "idem"),
    "bidoof": ("NON", "castor"),
    "bibarel": ("NON", "idem"),
    "buneary": ("NON", "lapin"),
    "lopunny": ("NON", "idem"),
    "glameow": ("NON", "chat"),
    "purugly": ("NON", "idem"),
    "patrat": ("NON", "vigie"),
    "watchog": ("NON", "idem"),
    "minccino": ("PEUT-ÊTRE", "chante et nettoie en rythme"),
    "cinccino": ("PEUT-ÊTRE", "idem"),
    "deerling": ("NON", "faon"),
    "sawsbuck": ("NON", "idem"),
    "rufflet": ("NON", "aigle"),
    "braviary": ("PEUT-ÊTRE", "cri de guerre d'aigle"),
    "bunnelby": ("NON", "lapin"),
    "diggersby": ("NON", "idem"),
    "yungoos": ("NON", "mangoufte"),
    "gumshoos": ("NON", "idem"),
    "stufful": ("PEUT-ÊTRE", "petits cris selon le Pokédex"),
    "bewear": ("NON", "ours câlin"),
    "furfrou": ("NON", "caniche"),
    "oranguru": ("NON", "orang-outan sage"),
    "komala": ("NON", "koala dormant"),
    "drampa": ("OUI", "grand-père dragon, parle aux enfants, ronronnements bienveillants"),
    "ditto": ("NON", "transformation"),
    # ── Ditto formes ─────────────────────────────────────────────────────────
    "eevee": ("NON", "renard évolution"),
    "vaporeon": ("NON", "idem"),
    "jolteon": ("NON", "idem"),
    "flareon": ("NON", "idem"),
    "espeon": ("NON", "idem"),
    "umbreon": ("NON", "idem"),
    "leafeon": ("NON", "idem"),
    "glaceon": ("NON", "idem"),
    "sylveon": ("OUI", "rubans qui captent les sons, chant envoûtant de type Fée"),
    "oricorio": ("OUI", "oiseau danseur/chanteur, style différent selon la fleur"),
    "oricorio pom pom": ("OUI", "idem"),
    "oricorio pau": ("OUI", "idem"),
    "oricorio sensu": ("OUI", "idem"),
    # ── Dragon ───────────────────────────────────────────────────────────────
    "dratini": ("NON", "serpent dragon"),
    "dragonair": ("NON", "idem"),
    "dragonite": ("PEUT-ÊTRE", "rugissements de dragon bienveillant"),
    "larvitar": ("NON", "larve dragon"),
    "pupitar": ("NON", "cocon dragon"),
    "tyranitar": ("OUI", "rugissements si puissants qu'ils détruisent les montagnes"),
    "bagon": ("NON", "dragon tête dure"),
    "shelgon": ("NON", "idem"),
    "salamence": ("OUI", "rugissements rageurs selon le Pokédex"),
    "beldum": ("NON", "acier psychique"),
    "metang": ("NON", "idem"),
    "metagross": ("NON", "idem"),
    "gible": ("NON", "petit dragon sol"),
    "gabite": ("NON", "idem"),
    "garchomp": ("NON", "requin dragon"),
    "deino": ("OUI", "aveugle, utilise les sons et la morsure pour explorer"),
    "zweilous": ("PEUT-ÊTRE", "deux têtes qui se disputent bruyamment"),
    "hydreigon": ("PEUT-ÊTRE", "idem, trois têtes"),
    "goomy": ("NON", "escargot dragon"),
    "sliggoo": ("NON", "idem"),
    "goodra": ("NON", "idem"),
    "jangmo-o": ("OUI", "claque ses écailles pour s'entraîner, mélodie de combat"),
    "hakamo-o": ("OUI", "idem"),
    "kommo-o": ("OUI", "chant de combat résonnant avec ses écailles"),
    # ── Fantôme/Divers ───────────────────────────────────────────────────────
    "spiritomb": ("PEUT-ÊTRE", "108 esprits qui murmurent"),
    "mimikyu": ("NON", "déguisement Pikachu"),
    "dhelmise": ("NON", "algue/ancre fantôme"),
    "tropius": ("NON", "dinosaure plante"),
    "carnivine": ("NON", "plante carnivore"),
    "maractus": ("OUI", "cactus qui danse au rythme de ses propres sons de maracas"),
    "stunfisk": ("NON", "flet électrique"),
    "delibird": ("NON", "manchot cadeau"),
    "cryogonal": ("NON", "flocon cristallin"),
    "farfetch'd": ("NON", "canard poireau"),
    "kangaskhan": ("NON", "kangourou"),
    "tauros": ("NON", "taureau"),
    "girafarig": ("PEUT-ÊTRE", "deux têtes, queue parlante selon le Pokédex"),
    "dunsparce": ("NON", "serpent normal"),
    "stantler": ("PEUT-ÊTRE", "bois de renne créent des illusions sonores"),
    "smeargle": ("NON", "peintre"),
    "miltank": ("NON", "vache"),
    "spinda": ("NON", "panda tournoyant"),
    "zangoose": ("NON", "mangouste"),
    "castform": ("NON", "météo"),
    "kecleon": ("NON", "caméléon"),
    "audino": ("OUI", "détecte les sons avec ses antennes, médecin sonore"),
    "bouffalant": ("NON", "bison afro"),
    "seviper": ("NON", "serpent poison"),
    "unown": ("PEUT-ÊTRE", "émet une énergie psychique mystérieuse"),
    "sigilyph": ("NON", "hiéroglyphe"),
    "lunatone": ("NON", "météorite lune"),
    "solrock": ("NON", "météorite soleil"),
    "carbink": ("NON", "diamant"),
    "skarmory": ("NON", "oiseau métal"),
    "mawile": ("NON", "acier"),
    "klefki": ("PEUT-ÊTRE", "tinte comme des clés"),
    "lapras": ("OUI", "chante des chansons de voyage, communique par mélodies"),
    "qwilfish": ("NON", "poisson épines"),
    "corsola": ("NON", "corail"),
    "relicanth": ("NON", "poisson fossile"),
    "luvdisc": ("NON", "poisson cœur"),
    "basculin": ("NON", "poisson agressif"),
    "alomomola": ("NON", "poisson soin"),
    "wishiwashi": ("PEUT-ÊTRE", "pleurs qui attirent les autres"),
    "wishiwashi school": ("PEUT-ÊTRE", "idem"),
    "pyukumuku": ("NON", "holothurie"),
    "bruxish": ("PEUT-ÊTRE", "grince des dents psychiquement"),
    # ── Lugia/Ho-Oh et légendaires ───────────────────────────────────────────
    "articuno": ("NON", "oiseau glace"),
    "zapdos": ("PEUT-ÊTRE", "foudre, crépitements électriques"),
    "moltres": ("NON", "oiseau feu"),
    "mewtwo": ("NON", "psychique"),
    "mew": ("PEUT-ÊTRE", "cris aigus joyeux"),
    "raikou": ("PEUT-ÊTRE", "tonnerre, cris électriques"),
    "entei": ("PEUT-ÊTRE", "rugissements volcaniques"),
    "suicune": ("NON", "vent silencieux"),
    "lugia": ("OUI", "chant de Lugia légendaire, pokémon gardien des mers"),
    "ho-oh": ("OUI", "chant d'oiseau phénix qui ressuscite"),
    "celebi": ("NON", "fée temps"),
    "regirock": ("NON", "golem roche"),
    "regice": ("NON", "golem glace"),
    "registeel": ("NON", "golem acier"),
    "regigigas": ("NON", "titan"),
    "latias": ("OUI", "cris ultrasoniques pour communiquer"),
    "latios": ("OUI", "idem, parle télépathiquement mais aussi vocalement"),
    "kyogre": ("OUI", "chants de baleine cosmiques selon le Pokédex"),
    "groudon": ("NON", "continent"),
    "rayquaza": ("OUI", "rugissements célestes"),
    "jirachi": ("NON", "étoile souhait"),
    "deoxys": ("NON", "virus alien"),
    "deoxys attack": ("NON", "idem"),
    "deoxys defense": ("NON", "idem"),
    "deoxys speed": ("NON", "idem"),
    "uxie": ("NON", "psychique"),
    "mesprit": ("NON", "idem"),
    "azelf": ("NON", "idem"),
    "dialga": ("NON", "temps"),
    "palkia": ("NON", "espace"),
    "giratina origin": ("NON", "antimonde"),
    "giratina altered forme": ("NON", "idem"),
    "heatran": ("NON", "acier feu"),
    "cresselia": ("NON", "lune"),
    "darkrai": ("PEUT-ÊTRE", "murmures de cauchemar"),
    "phione": ("NON", "eau"),
    "manaphy": ("OUI", "chante pour relier les cœurs des créatures marines"),
    "shaymin": ("NON", "hérisson fleur"),
    "shaymin sky": ("NON", "idem"),
    "arceus": ("NON", "dieu"),
    "victini": ("NON", "victoire psychique"),
    "cobalion": ("NON", "épée acier"),
    "terrakion": ("NON", "roche combat"),
    "virizion": ("NON", "herbe combat"),
    "keldeo": ("NON", "eau combat"),
    "tornadus": ("PEUT-ÊTRE", "vent, son des tempêtes"),
    "tornadus therian": ("PEUT-ÊTRE", "idem"),
    "thundurus": ("OUI", "tonnerre, coups de foudre bruyants"),
    "thundurus therian": ("OUI", "idem"),
    "landorus": ("NON", "terre"),
    "landorus therian": ("NON", "idem"),
    "reshiram": ("OUI", "rugissements idéalistes ardents"),
    "zekrom": ("OUI", "mugissements électriques"),
    "kyurem": ("PEUT-ÊTRE", "cris de glace solitaire"),
    "kyurem white": ("OUI", "fusion avec Reshiram, rugissements"),
    "kyurem black": ("OUI", "fusion avec Zekrom"),
    "meloetta aria forme": ("OUI", "la voix de Meloetta change la météo, légendaire du son"),
    "meloetta step forme": ("OUI", "danse et chant, légendaire du son"),
    "meloetta": ("OUI", "idem"),
    "meloetta pirouette": ("OUI", "idem"),
    "genesect": ("NON", "insecte fossile tech"),
    "genesect douse drive": ("NON", "idem"),
    "genesect shock drive": ("NON", "idem"),
    "genesect burn drive": ("NON", "idem"),
    "genesect chill drive": ("NON", "idem"),
    "xerneas": ("NON", "vie"),
    "yveltal": ("PEUT-ÊTRE", "cri de mort"),
    "zygarde 10% forme": ("NON", "ordre"),
    "zygarde 50% forme": ("NON", "idem"),
    "zygarde complete forme": ("NON", "idem"),
    "diancie": ("NON", "diamant fée"),
    "hoopa confined": ("PEUT-ÊTRE", "rires espiègles"),
    "hoopa unbound": ("PEUT-ÊTRE", "idem"),
    "volcanion": ("NON", "vapeur feu"),
    "type: null": ("NON", "chimère"),
    "silvally": ("NON", "idem"),
    "tapu koko": ("NON", "gardien électrique"),
    "tapu lele": ("NON", "gardien psychique"),
    "tapu bulu": ("NON", "gardien plante"),
    "tapu fini": ("NON", "gardien eau"),
    "cosmog": ("NON", "nébuleuse"),
    "cosmoem": ("NON", "idem"),
    "solgaleo": ("NON", "soleil lion"),
    "lunala": ("NON", "lune chauve-souris"),
    "necrozma": ("NON", "lumière"),
    "necrozma dusk mane": ("NON", "idem"),
    "necrozma dawn wings": ("NON", "idem"),
    "nihilego": ("NON", "méduse ultra"),
    "buzzwole": ("NON", "moustique ultra"),
    "pheromosa": ("NON", "blatte ultra"),
    "xurkitree": ("PEUT-ÊTRE", "arbre électrique, bourdonnement"),
    "celesteela": ("NON", "roseau ultra"),
    "kartana": ("NON", "origami ultra"),
    "guzzlord": ("NON", "glouton ultra"),
    "poipole": ("NON", "poison ultra"),
    "naganadel": ("NON", "idem"),
    "stakataka": ("NON", "mur ultra"),
    "blacephalon": ("OUI", "explosion de feux d'artifice bruyants"),
    "magearna": ("NON", "machine acier"),
    "marshadow": ("NON", "ombre combat"),
    "zeraora": ("PEUT-ÊTRE", "électrique, grondements"),
    # ── Gen 8 ────────────────────────────────────────────────────────────────
    "grookey": ("OUI", "joue du bâton sur des surfaces en rythme"),
    "thwackey": ("OUI", "tambourine avec deux bâtons"),
    "rillaboom": ("OUI", "gorille tamborinaire, son puissant qui fait pousser les plantes"),
    "scorbunny": ("NON", "lapin feu"),
    "raboot": ("NON", "idem"),
    "cinderace": ("NON", "footballeur feu"),
    "sobble": ("PEUT-ÊTRE", "pleurs contagieux"),
    "drizzile": ("NON", "lézard espion"),
    "inteleon": ("NON", "espion eau"),
    "skwovet": ("NON", "écureuil"),
    "greedent": ("NON", "idem"),
    "rookidee": ("NON", "oiseau acier"),
    "corvisquire": ("NON", "idem"),
    "corviknight": ("NON", "idem"),
    "blipbug": ("NON", "larve"),
    "dottler": ("NON", "idem"),
    "orbeetle": ("PEUT-ÊTRE", "coccinelle psychique, ondes cérébrales"),
    "nickit": ("NON", "renard furtif"),
    "thievul": ("NON", "idem"),
    "gossifleur": ("NON", "fleur"),
    "eldegoss": ("NON", "idem"),
    "wooloo": ("NON", "mouton"),
    "dubwool": ("NON", "idem"),
    "chewtle": ("NON", "tortue"),
    "drednaw": ("NON", "idem"),
    "yamper": ("NON", "chien électrique"),
    "boltund": ("NON", "idem"),
    "rolycoly": ("NON", "charbon"),
    "carkol": ("NON", "idem"),
    "coalossal": ("NON", "idem"),
    "applin": ("NON", "pomme dragon"),
    "flapple": ("NON", "idem"),
    "appletun": ("NON", "idem"),
    "silicobra": ("NON", "cobra sable"),
    "sandaconda": ("NON", "idem"),
    "cramorant": ("NON", "cormoran"),
    "arrokuda": ("NON", "barracuda"),
    "barraskewda": ("NON", "idem"),
    "toxel": ("OUI", "bébé électrique/poison, cris toxiques électrisés"),
    "toxtricity": ("OUI", "rock punk, joue de la guitare avec son corps"),
    "toxtricity low key": ("OUI", "idem"),
    "sizzlipede": ("NON", "chenille feu"),
    "centiskorch": ("NON", "idem"),
    "clobbopus": ("NON", "pieuvre combat"),
    "grapploct": ("NON", "idem"),
    "sinistea": ("NON", "fantôme thé"),
    "polteageist": ("NON", "idem"),
    "hatenna": ("NON", "psychique chapeau"),
    "hattrem": ("NON", "idem"),
    "hatterene": ("NON", "idem"),
    "impidimp": ("NON", "diablotin"),
    "morgrem": ("NON", "idem"),
    "grimmsnarl": ("NON", "idem"),
    "milcery": ("NON", "crème fée"),
    "alcremie": ("NON", "idem"),
    "falinks": ("NON", "formation militaire"),
    "pincurchin": ("NON", "oursin électrique"),
    "snom": ("NON", "larve glace"),
    "frosmoth": ("NON", "papillon glace"),
    "stonjourner": ("NON", "roche"),
    "eiscue ice face": ("NON", "manchot glace"),
    "eiscue noice face": ("NON", "idem"),
    "indeedee male": ("OUI", "psychique, émet des signaux sonores/empathiques"),
    "indeedee female": ("OUI", "idem"),
    "indeedee": ("OUI", "idem"),
    "morpeko": ("NON", "hamster électrique"),
    "cufant": ("NON", "éléphanteau acier"),
    "copperajah": ("PEUT-ÊTRE", "éléphant, barrissements"),
    "dracozolt": ("NON", "fossile électrique"),
    "arctozolt": ("NON", "fossile glace"),
    "dracovish": ("NON", "fossile eau"),
    "arctovish": ("NON", "fossile glace"),
    "duraludon": ("NON", "acier dragon"),
    "dreepy": ("NON", "fantôme dragon"),
    "drakloak": ("NON", "idem"),
    "dragapult": ("NON", "idem"),
    # Galarian
    "meowth galar": ("NON", "chat acier"),
    "perrserker": ("NON", "idem"),
    "ponyta galar": ("NON", "licorne psychique"),
    "rapidash galar": ("NON", "idem"),
    "farfetch'd galar": ("NON", "idem"),
    "sirfetch'd": ("NON", "idem"),
    "weezing galar": ("NON", "poison industriel"),
    "mr mime galar": ("OUI", "chante et danse"),
    "corsola galar": ("NON", "corail fantôme"),
    "cursola": ("NON", "idem"),
    "zigzagoon galar": ("NON", "raton punk"),
    "linoone galar": ("NON", "idem"),
    "obstagoon": ("OUI", "rockeur, hurlements de défiance, style punk"),
    "darumaka galar": ("NON", "daruma glace"),
    "darmanitan galar": ("NON", "idem"),
    "darmanitan zen mode galar": ("NON", "idem"),
    "yamask galar": ("NON", "rune fantôme"),
    "runerigus": ("NON", "idem"),
    "stunfisk galar": ("NON", "flet acier"),
    "slowpoke galar": ("NON", "idem"),
    "slowbro galar": ("NON", "idem"),
    "slowking galar": ("NON", "idem"),
    "zacian hero of many battles forme": ("NON", "épée légendaire"),
    "zacian crowned sword forme": ("NON", "idem"),
    "zamazenta hero of many battles forme": ("NON", "bouclier légendaire"),
    "zamazenta crowned shield forme": ("NON", "idem"),
    "eternatus": ("NON", "énergie cosmique"),
    "meltan": ("NON", "hexagone métal"),
    "melmetal": ("NON", "idem"),
    "kubfu": ("NON", "combat"),
    "urshifu": ("NON", "idem"),
    "urshifu rapid strike style": ("NON", "idem"),
    "zarude": ("PEUT-ÊTRE", "singe bosseur solitaire"),
    "zarude dada": ("PEUT-ÊTRE", "idem"),
    "articuno galar": ("NON", "oiseau psychique"),
    "zapdos galar": ("NON", "oiseau combat"),
    "moltres galar": ("NON", "oiseau ténèbres"),
    "regieleki": ("PEUT-ÊTRE", "électrique pur, bourdonnement"),
    "regidrago": ("PEUT-ÊTRE", "rugissements dragon cristal"),
    "glastrier": ("NON", "cheval glace"),
    "spectrier": ("PEUT-ÊTRE", "cheval fantôme, galop spectral"),
    "calyrex": ("NON", "psychique plante"),
    "calyrex ice rider": ("NON", "idem"),
    "calyrex shadow rider": ("NON", "idem"),
    # Gen 9
    "sprigatito": ("NON", "chaton herbe"),
    "floragato": ("NON", "idem"),
    "meowscarada": ("NON", "magicienne"),
    "fuecoco": ("NON", "croco feu"),
    "crocalor": ("NON", "idem"),
    "skeledirge": ("OUI", "chante pour purifier les âmes et craquer des flammes"),
    "quaxly": ("NON", "canard eau"),
    "quaxwell": ("NON", "idem"),
    "quaquaval": ("OUI", "danseur carnavalesque, danse au rythme de musiques festives"),
    "lechonk": ("NON", "cochon"),
    "oinkologne (m)": ("NON", "idem"),
    "oinkologne (f)": ("NON", "idem"),
    "oinkologne": ("NON", "idem"),
    "dudunsparce": ("NON", "serpent normal évolué"),
    "tarountula": ("NON", "araignée"),
    "spidops": ("NON", "idem"),
    "nymble": ("NON", "criquet"),
    "lokix": ("NON", "idem"),
    "rellor": ("NON", "bousier"),
    "rabsca": ("NON", "idem"),
    "greavard": ("NON", "chien fantôme"),
    "houndstone": ("NON", "idem"),
    "flittle": ("NON", "psychique"),
    "espathra": ("NON", "idem"),
    "farigiraf": ("OUI", "deux têtes, queue qui parle, sons doubles"),
    "wiglett": ("NON", "taupe eau"),
    "wugtrio": ("NON", "idem"),
    "dondozo": ("OUI", "poisson-chat colossal, rugissements sous-marins"),
    "veluza": ("NON", "poisson psychique"),
    "finizen": ("OUI", "dauphin, sons ultrasoniques"),
    "palafin": ("OUI", "idem"),
    "palafin (hero form)": ("OUI", "idem"),
    "smoliv": ("NON", "olive herbe"),
    "dolliv": ("NON", "idem"),
    "arboliva": ("NON", "idem"),
    "capsakid": ("NON", "piment herbe"),
    "scovillain": ("NON", "idem"),
    "tadbulb": ("NON", "bulbe électrique"),
    "bellibolt": ("PEUT-ÊTRE", "grenouille électrique, couinements électriques"),
    "varoom": ("PEUT-ÊTRE", "moteur, vrombissement"),
    "revavroom": ("PEUT-ÊTRE", "idem, vroom"),
    "orthworm": ("NON", "ver métal"),
    "tandemaus": ("NON", "souris"),
    "maushold": ("NON", "famille souris"),
    "cetoddle": ("OUI", "baleineau, chante des mélodies simples"),
    "cetitan": ("OUI", "baleine terrestre, chante en marchant"),
    "frigibax": ("NON", "dragon glace"),
    "arctibax": ("NON", "idem"),
    "baxcalibur": ("NON", "idem"),
    "tatsugiri": ("NON", "sushi dragon"),
    "cyclizar": ("NON", "lézard moto"),
    "pawmi": ("NON", "souris électrique"),
    "pawmo": ("NON", "idem"),
    "pawmot": ("NON", "idem"),
    "wattrel": ("PEUT-ÊTRE", "oiseau électrique, cri"),
    "kilowattrel": ("PEUT-ÊTRE", "idem"),
    "bombirdier": ("NON", "oiseau bombardier"),
    "squawkabilly": ("OUI", "perroquet criard, squawk = cri"),
    "squawkabilly white": ("OUI", "idem"),
    "squawkabilly yellow": ("OUI", "idem"),
    "squawkabilly blue": ("OUI", "idem"),
    "squawkabilly green plumage": ("OUI", "idem"),
    "flamigo": ("NON", "flamant rose"),
    "klawf": ("NON", "crabe roche"),
    "nacli": ("NON", "sel roche"),
    "naclstack": ("NON", "idem"),
    "garganacl": ("NON", "idem"),
    "glimmet": ("NON", "cristal poison"),
    "glimmora": ("NON", "idem"),
    "shroodle": ("NON", "musaraigne poison"),
    "grafaiai": ("NON", "primate poison"),
    "fidough": ("NON", "chien pain"),
    "dachsbun": ("NON", "idem"),
    "maschiff": ("NON", "mâtin"),
    "mabosstiff": ("NON", "idem"),
    "bramblin": ("NON", "buisson fantôme"),
    "brambleghast": ("NON", "idem"),
    "gimmighoul": ("NON", "trésor fantôme"),
    "gimmighoul roaming": ("NON", "idem"),
    "gholdengo": ("NON", "pièce d'or"),
    "great tusk": ("NON", "paradoxe"),
    "brute bonnet": ("NON", "idem"),
    "sandy shocks": ("NON", "idem"),
    "scream tail": ("OUI", "queue qui crie, attaque par cris stridents - Paradoxe Jigglypuff"),
    "flutter mane": ("OUI", "Paradoxe Misdreavus, gémissements"),
    "slither wing": ("NON", "Paradoxe Volcarona"),
    "roaring moon": ("OUI", "Paradoxe Salamence, rugissements lunaires"),
    "iron treads": ("NON", "Paradoxe Donphan"),
    "iron moth": ("NON", "Paradoxe Volcarona"),
    "iron hands": ("NON", "Paradoxe Hariyama"),
    "iron jugulis": ("NON", "Paradoxe Hydreigon"),
    "iron thorns": ("NON", "Paradoxe Tyranitar"),
    "iron bundle": ("NON", "Paradoxe Delibird"),
    "iron valiant": ("NON", "Paradoxe Gardevoir/Gallade"),
    "ting lu": ("NON", "Ancien Pokémon vase"),
    "chien pao": ("NON", "Ancien Pokémon épée"),
    "wo chien": ("NON", "Ancien Pokémon tablette"),
    "chi yu": ("OUI", "Ancien Pokémon perle, souffle ardent rugissant"),
    "koraidon": ("OUI", "rugissements du passé"),
    "miraidon": ("PEUT-ÊTRE", "bourdonnements futuristes"),
    "tinkatink": ("PEUT-ÊTRE", "martèle des métaux, tintements"),
    "tinkatuff": ("PEUT-ÊTRE", "idem"),
    "tinkaton": ("OUI", "coups de marteau créent des sons énormes, communique par bruit"),
    "charcadet": ("NON", "charbon fantôme"),
    "armarouge": ("NON", "idem"),
    "ceruledge": ("NON", "idem"),
    "toedscool": ("NON", "champignon eau"),
    "toedscruel": ("NON", "idem"),
    "kingambit": ("NON", "acier"),
    "paldean wooper": ("NON", "axolotl poison"),
    "clodsire": ("NON", "idem"),
    "annihilape": ("OUI", "rage qui résonne dans l'au-delà, hurlements spectraux"),
    "paldean tauros": ("NON", "taureau"),
    "paldean tauros blaze breed": ("NON", "idem"),
    "paldean tauros aqua breed": ("NON", "idem"),
    "walking wake": ("OUI", "Paradoxe Suicune, rugissements de l'éveil"),
    "iron leaves": ("NON", "Paradoxe Virizion"),
    "gouging fire": ("OUI", "Paradoxe Entei, rugissements ardents"),
    "raging bolt": ("OUI", "Paradoxe Raikou, grondements électriques"),
    "iron boulder": ("NON", "Paradoxe Terrakion"),
    "iron crown": ("NON", "Paradoxe Cobalion"),
    "dipplin": ("NON", "pomme dragon"),
    "hydrapple": ("NON", "idem"),
    "poltchageist": ("NON", "thé fantôme"),
    "sinistcha": ("NON", "idem"),
    "okidogi": ("NON", "chien poison"),
    "munkidori": ("NON", "singe poison"),
    "fezandipiti": ("NON", "faisan poison"),
    "ogerpon": ("NON", "masque herbe"),
    "ogerpon wellspring mask": ("NON", "idem"),
    "ogerpon hearthflame": ("NON", "idem"),
    "ogerpon cornerstone": ("NON", "idem"),
    "ogerpon wellspring": ("NON", "idem"),
    "ursaluna (bloodmoon)": ("OUI", "rugissements lunaires sanglants"),
    "archaludon": ("NON", "pont acier"),
    "terapagos": ("NON", "cristal légendaire"),
    "pecharunt": ("NON", "mochi fantôme"),
    # ── Paradoxes et légendaires restants ────────────────────────────────────
    "necrozma ultra": ("NON", "lumière ultime"),
    "dusk mane": ("NON", "Necrozma"),
    "dawn wings": ("NON", "idem"),
    "kartana fallen": ("NON", "origami"),
    "iron heart": ("NON", "Paradoxe Blissey"),
    "iron exo": ("NON", "Paradoxe"),
    # ── Eeveelutions custom ───────────────────────────────────────────────────
    "automateon": ("NON", "évolution mécanique"),
    "aviateon": ("NON", "évolution vol"),
    "champeon": ("NON", "évolution combat"),
    "companeon": ("PEUT-ÊTRE", "compagnon, communication"),
    "corroseon": ("NON", "évolution poison"),
    "draconeon": ("NON", "évolution dragon"),
    "dungeon": ("NON", "évolution donjon"),
    "illuseon": ("NON", "évolution illusion"),
    "obsideon": ("NON", "évolution obsidienne"),
    "scorpeon": ("NON", "évolution scorpion"),
    # ── Pokémon custom originaux ──────────────────────────────────────────────
    "phantowl": ("OUI", "fantôme/chouette - hululements spectraux"),
    "duelumber": ("NON", "duel/arbre"),
    "arachtres": ("NON", "araignée trio"),
    "flairgrance": ("NON", "parfum/flair"),
    "arashinne": ("NON", "tempête japonaise"),
    "dreadnaut": ("NON", "crustacé nautile"),
    "boarlock": ("NON", "sanglier verrou"),
    "heliomodo": ("NON", "helio/lézard"),
    "sopranice": ("OUI", "soprano + glace - voix de soprano glaciale, attaque sonore évidente"),
    "beefender": ("NON", "bœuf défenseur"),
    "salazarus": ("NON", "salamandre ténèbres"),
    "gooschase": ("NON", "oie chasseuse"),
    "lepastry": ("NON", "lièvre pâtisserie"),
    "tortemple": ("NON", "tortue temple"),
    "brontonana": ("NON", "bronto banane"),
    "dredwood": ("NON", "bois lourd"),
    "corm": ("NON", "bulbe plante"),
    "cormoth": ("NON", "idem"),
    "popcorm": ("NON", "idem pop"),
    "cormoth mega": ("NON", "idem"),
    "popcorm mega": ("NON", "idem"),
    "blizzard maw": ("NON", "gueule blizzard"),
    "lumber sloth": ("NON", "paresseux bûcheron"),
    "lumbering sloth engulfed": ("NON", "idem"),
    "iron carapace": ("NON", "carapace métal"),
    "magnemous": ("PEUT-ÊTRE", "magneto + famous, signaux magnétiques/sonores"),
    "kaiosea": ("PEUT-ÊTRE", "kaio + mer, rugissements marins"),
    "slyduck": ("NON", "canard rusé"),
    "shyduck": ("NON", "canard timide"),
    "marbeep": ("OUI", "bip + bille - émet des bips, clairement sonore"),
    "fluffbee": ("OUI", "abeille floue - bourdonnement d'abeille"),
    "amphybuzz": ("OUI", "amphibien + buzz - vibrations amphibiennes sonores"),
    "amphybuzz mega": ("OUI", "idem mega"),
    "bariong": ("PEUT-ÊTRE", "baryton + lion - rugissements de baryton"),
    "crabruiser": ("NON", "crabe brute"),
    "phanfernal": ("NON", "fantôme infernal"),
    "skulberus": ("NON", "crâne cerbère"),
    "velozel": ("NON", "vélo gazelle"),
    "bewarden": ("NON", "bewear gardien"),
    "bubbleo": ("NON", "bulle"),
    "hydroar": ("OUI", "hydro + roar, rugissements aquatiques"),
    "hydroar f": ("OUI", "idem femelle"),
    "granitun": ("NON", "granit + thon"),
    "fujiflap": ("NON", "fuji + nageoire"),
    "knaiver": ("NON", "couteau"),
    "sagaracas": ("NON", "sagara + castor"),
    "lucineon": ("PEUT-ÊTRE", "luciole + néon, signaux lumineux/sonores"),
    "crawdauntles": ("NON", "crawdaunt impavide"),
    "crawdauntless": ("NON", "idem"),
    "iron voca": ("OUI", "vocal + métal Paradoxe - vocaliste robotique, évident"),
    "frostula": ("NON", "frost + dracula"),
    "goodra mega": ("NON", "idem"),
    "slowbro mega galarian": ("NON", "idem"),
    "slowking mega galarian": ("NON", "idem"),
    "dududunsparce": ("NON", "serpent normal triple"),
    "dududunsparce mega": ("NON", "idem"),
    "bewarden redux": ("NON", "idem"),
    "seerkat": ("NON", "suricate voyant"),
    "tentagrewl": ("NON", "tentacule grognard"),
    "cacjack": ("NON", "cactus jack"),
    "tyranjoula": ("NON", "tyrannosaure tarantule"),
    "crag hopper": ("NON", "sauteur roche"),
    "dedelibird": ("NON", "delibird diable"),
    "krampird": ("NON", "krampus oiseau"),
    "iron palette": ("NON", "palette métal"),
    "carbonix": ("NON", "carbone phoenix"),
    "wispywaspy": ("PEUT-ÊTRE", "spectre guêpe, bourdonnement fantomatique"),
    "wispywaspy hivemind": ("PEUT-ÊTRE", "idem ruche, signal sonore de ruche"),
    "iron scythe": ("NON", "faux métal"),
    "wooly worm": ("NON", "ver laineux"),
    "heracreus": ("NON", "hercule acier"),
    "heracreus mega": ("NON", "idem"),
    "grotom": ("PEUT-ÊTRE", "Rotom pirate - peut habiter appareils sonores"),
    "grotom glass": ("NON", "Rotom verre"),
    "grotom roll": ("PEUT-ÊTRE", "Rotom rouleau"),
    "grotom drum": ("OUI", "Rotom + batterie - clairement sonore"),
    "grotom kick": ("NON", "Rotom + kick"),
    "grotom fill": ("PEUT-ÊTRE", "Rotom + fill de batterie"),
    "orchestot": ("OUI", "orchestre + robot - entité musicale pure, évidemment Son"),
    "queengambit": ("NON", "reine + échecs"),
    "pentadug": ("NON", "pentagone + creuseur"),
    "pentadug alolan": ("NON", "idem"),
    "crabominable mega": ("NON", "idem"),
    "abyssand": ("NON", "abysse + sable"),
    "pentawug": ("NON", "pentagone + grenouille"),
    "ratiking": ("NON", "rat roi"),
    "ratfioso": ("NON", "rat mafieux"),
    "guardozel": ("NON", "garde + gazelle"),
    "beniccino": ("NON", "benni + piccino"),
    "torrentula": ("NON", "torrent + tarantule"),
    "spindaze": ("NON", "spin + éblouissement"),
    "blocli": ("NON", "bloc + cli"),
    "bloxtack": ("NON", "bloc + attaque"),
    "gargablox": ("NON", "gargouille + bloc"),
    "hippopotato": ("NON", "hippopotame + patate"),
    "hippotaton": ("NON", "idem évolué"),
    "corn tyrant": ("NON", "maïs tyran"),
    "iron spirals": ("NON", "spirales métal"),
    "iron saber": ("NON", "sabre métal"),
    "hypnocroak": ("OUI", "Hypno + Toxicroak = croassement hypnotique, lien sonore fort"),
    "plundertow": ("NON", "pilleur + remorqueur"),
    # ── Alolan ───────────────────────────────────────────────────────────────
    "rattata alola": ("NON", "rat"),
    "raticate alola": ("NON", "idem"),
    "sandshrew alola": ("NON", "pangolin glace"),
    "sandslash alola": ("NON", "idem"),
    "vulpix alola": ("NON", "renard glace"),
    "ninetales alola": ("PEUT-ÊTRE", "malédictions murmurées"),
    "diglett alola": ("NON", "taupe"),
    "dugtrio alola": ("NON", "idem"),
    "meowth alola": ("NON", "chat"),
    "persian alola": ("NON", "idem"),
    "geodude alola": ("NON", "roche"),
    "graveler alola": ("NON", "idem"),
    "golem alola": ("NON", "idem"),
    "grimer alola": ("NON", "boue"),
    "muk alola": ("NON", "idem"),
    # ── Fossiles ─────────────────────────────────────────────────────────────
    "omanyte": ("NON", "ammonite"),
    "omastar": ("NON", "idem"),
    "kabuto": ("NON", "trilobite"),
    "kabutops": ("NON", "idem"),
    "lileep": ("NON", "crinoïde"),
    "cradily": ("NON", "idem"),
    "anorith": ("NON", "anomalocaris"),
    "armaldo": ("NON", "idem"),
    "cranidos": ("NON", "pachycéphalosaurus"),
    "rampardos": ("NON", "idem"),
    "shieldon": ("NON", "protoceratops"),
    "bastiodon": ("NON", "idem"),
    "tirtouga": ("NON", "tortue fossile"),
    "carracosta": ("NON", "idem"),
    "archen": ("NON", "archéoptéryx"),
    "archeops": ("PEUT-ÊTRE", "oiseau primitif, cris archaïques"),
    "tyrunt": ("NON", "tyrannosaure"),
    "tyrantrum": ("OUI", "rugissements de roi, T-rex, 'its roar once shook the mountains'"),
    "amaura": ("NON", "dinosaure glace"),
    "aurorus": ("OUI", "chante pour le groupe comme une baleine arctique"),
    "aerodactyl": ("PEUT-ÊTRE", "ptérodactyle, cri préhistorique"),
    # ── Pseudo-légendaires ───────────────────────────────────────────────────
    # ── Formes delta ─────────────────────────────────────────────────────────
    # (les formes delta héritent de leur base, sauf indication contraire)
}

# ─── Règles héritées pour formes delta/redux/mega/hisuian ────────────────────
def get_base_name(name):
    """Extrait le nom de base depuis une forme spéciale."""
    suffixes = [
        " delta form", " redux", " mega y", " mega x", " mega z", " mega",
        " hisuian mega", " hisuian", " primal", " origin forme", " origin",
        " apex", " partner", " alolan mega", " galarian", " galar", " x", " y", " z",
        " battle bond", " pirouette", " aria forme", " step forme",
        " blade", " shield", " sword", " crowned",
        " ice face", " noice face", " hero of many battles forme",
        " crowned sword forme", " crowned shield forme",
        " rapid strike style mega", " rapid strike style",
        " ice rider", " shadow rider", " cloud rider",
        " spider form", " ruin form",
        " water form", " fairy form",
        " berry form", " cake form",
        " magician form", " mime form",
        " confined form", " umbound form",
        " three segment", " three",
        " four", " small", " large", " super",
        " heat", " wash", " frost", " fan", " mow",
        " midday", " midnight", " dusk", " eclipse", " twilight",
        " delivery", " kanto", " hoenn", " sinnoh", " unova",
        " kalos", " alola", " world", " cosplay",
        " rock star", " belle", " pop star", " ph d", " libre",
        " partner cap", " spiky",
        " summer", " autumn", " winter",
        " sandy", " trash", " eterna",
        " east", " west",
        " white", " blue", " red", " orange", " yellow", " green",
        " heart", " star", " diamond", " debutante", " matron",
        " dandy", " la reine", " kabuki", " pharaoh",
        " active", " busted", " cloud",
        " douse drive", " shock drive", " burn drive", " chill drive",
        " resolute", " zen mode",
        " school",
        " polar", " tundra", " continental", " gardens", " elegant",
        " meadow", " modern", " marine", " archipelago",
        " high plains", " sandstorm", " river", " monsoon",
        " savanna", " sun", " ocean", " jungle", " fancy", " pokéball",
        " eternal flower",
        " low key",
        " antique",
        " ruby", " matcha", " mint", " lemon", " salted",
        " ruby swirl", " caramel", " rainbow",
        " blaze breed", " aqua breed",
        " curly", " droopy", " stretchy",
        " hero form",
        " male", " female",
        " m", " f",
        " hangry",
        " pom pom", " pau", " sensu",
        " wellness", " hearthflame", " cornerstone", " wellspring",
    ]
    n = name
    for suf in sorted(suffixes, key=len, reverse=True):
        if n.endswith(suf):
            n = n[:-len(suf)].strip()
            break
    # Mots-clés génériques
    for kw in [" mega", " redux", " delta", " primal", " origin", " hisuian",
               " galarian", " alolan", " galar", " alola"]:
        if kw in n:
            n = n.replace(kw, "").strip()
    return n


def evaluate_sound(name):
    """Retourne (verdict, raison) pour un Pokémon donné."""
    n = name.lower().strip()

    # 1. Entrée explicite
    if n in SOUND_DATA:
        return SOUND_DATA[n]

    # 2. Héritage depuis le nom de base
    base = get_base_name(n)
    if base != n and base in SOUND_DATA:
        v, r = SOUND_DATA[base]
        return (v, r + " (forme dérivée)")

    # 3. Heuristiques basées sur le nom
    sound_keywords = [
        "drum", "bell", "song", "sing", "choir", "melody", "rhythm", "beat",
        "music", "vocal", "voca", "sopra", "orches", "canta", "chant", "hymn",
        "shout", "roar", "howl", "echo", "sonic", "buzz", "hum", "tone",
        "note", "sound", "voice", "cry", "scream", "wail", "shriek", "squawk",
        "beep", "boop", "horn", "pipe", "flute", "lute", "harp", "bass",
        "alto", "tenor", "treble", "opera", "toot", "blare", "jingle", "ring",
        "chirp", "tweet", "croak", "yell", "bellow", "bark",
    ]
    for kw in sound_keywords:
        if kw in n:
            return ("OUI", f"nom contient '{kw}', lien sonore évident")

    # Bourdonnements/insectes
    if any(k in n for k in ["wasp", "bee", "fly", "moth", "bug", "cricket", "cicada"]):
        return ("PEUT-ÊTRE", "insecte, bourdonnement ou cri possible")

    # Oiseaux
    if any(k in n for k in ["bird", "owl", "raven", "crow", "parrot", "canary", "robin"]):
        return ("PEUT-ÊTRE", "oiseau, cri possible")

    # Baleines/dauphins
    if any(k in n for k in ["whale", "dolphin", "porpoise", "orca"]):
        return ("OUI", "cétacé, chants sous-marins")

    # Dragons
    if any(k in n for k in ["dragon", "drake", "wyvern", "wyrm"]):
        return ("PEUT-ÊTRE", "dragon, rugissements possibles")

    # Loups/chiens
    if any(k in n for k in ["wolf", "hound", "dog", "pup", "bark"]):
        return ("PEUT-ÊTRE", "canidé, hurlements/aboiements")

    # Formes redux/mega sans base connue → neutre
    return ("NON", "pas de lien sonore identifiable d'après le nom")


# ─── Lecture du fichier source ────────────────────────────────────────────────
INPUT  = "list_pokemons.txt"
OUTPUT = "list_pokemon_finished.txt"

import os
script_dir = os.path.dirname(os.path.abspath(__file__))
input_path  = os.path.join(script_dir, INPUT)
output_path = os.path.join(script_dir, OUTPUT)

with open(input_path, encoding="utf-8") as f:
    lines = f.readlines()

# ─── Parsing par blocs ────────────────────────────────────────────────────────
# Chaque bloc = nom / ligne vide / "level up moves: " / ligne vide / "ct / egg moves: "
# On détecte le nom comme une ligne sans "level up" ni "ct / egg"

SKIP_LINES = {
    "pokédex update.",
    "full round.",
    "attack lowered by -1 combat stage.",
    "end.",
    "",
}

def is_name_line(line):
    stripped = line.rstrip("\n").strip()
    if stripped.lower() in SKIP_LINES:
        return False
    if stripped.lower().startswith("level up moves"):
        return False
    if stripped.lower().startswith("ct / egg moves"):
        return False
    if stripped == "":
        return False
    return True

out_lines = []
i = 0
while i < len(lines):
    raw = lines[i]
    stripped = raw.rstrip("\n").strip()

    # Lignes à passer telles quelles (marqueurs spéciaux)
    if stripped.lower() in SKIP_LINES and stripped != "":
        out_lines.append(raw)
        i += 1
        continue

    if is_name_line(raw):
        name = stripped
        verdict, reason = evaluate_sound(name)
        out_lines.append(f"{name}\n")
        out_lines.append("\n")
        out_lines.append(f"son: {verdict} — {reason}\n")
        out_lines.append("\n")
        i += 1
        # Sauter la ligne vide après le nom si présente
        if i < len(lines) and lines[i].strip() == "":
            i += 1
    else:
        out_lines.append(raw)
        i += 1

with open(output_path, "w", encoding="utf-8") as f:
    f.writelines(out_lines)

print(f"Terminé ! {output_path} généré.")
